language: node_js

node_js:
  - "0.12"

script:
  - ./node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --browsers PhantomJS

before_script:
  - npm install -g bower codeclimate-test-reporter
  - npm install

after_script:
  - cat coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: b5177481ec034a88423027b448c52517fe014c4bd8dcb2e857985998d6060941